export const authTypes = {
    SIGN_IN_REQUEST:'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCESS: 'LOGOUT_SUCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}