export const authTypes = {
    SIGN_IN_REQUEST:'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}


export const postTypes = {
    GET_ALL_POSTS_REQUEST:'GET_ALL_POSTS_REQUEST',
    GET_ALL_POSTS_SUCCESS:'GET_ALL_POSTS_SUCCESS',
    GET_ALL_POSTS_FAILURE:'GET_ALL_POSTS_FAILURE'
}