export const authTypes = {
    SIGN_IN_REQUEST:'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}


export const postTypes = {
    GET_ALL_POSTS_REQUEST:'GET_ALL_POSTS_REQUEST',
    GET_ALL_POSTS_SUCCESS:'GET_ALL_POSTS_SUCCESS',
    GET_ALL_POSTS_FAILURE:'GET_ALL_POSTS_FAILURE'
}

export const friendsTypes = {
    ADD_FRIEND_REQUEST:'ADD_FRIEND_REQUEST',
    ADD_FRIEND_SUCCESS:'ADD_FRIEND_SUCCESS',
    ADD_FRIEND_FAILURE:'ADD_FRIEND_FAILURE',
    ACCEPT_FRIEND_REQUEST:'ACCEPT_FRIEND_REQUEST',
    ACCEPT_FRIEND_SUCCESS:'ACCEPT_FRIEND_SUCCESS',
    ACCEPT_FRIEND_FAILURE:'ACCEPT_FRIEND_FAILURE',
    DENY_FRIEND_REQUEST:'DENY_FRIEND_REQUEST',
    DENY_FRIEND_SUCCESS:'DENY_FRIEND_SUCCESS',
    DENY_FRIEND_FAILURE:'DENY_FRIEND_FAILURE',
    DELETE_FRIEND_REQUEST:'DELETE_FRIEND_REQUEST',
    DELETE_FRIEND_SUCCESS:'DELETE_FRIEND_SUCCESS',
    DELETE_FRIEND_FAILURE:'DELETE_FRIEND_FAILURE'
}